source 'https://github.com/CocoaPods/Specs.git'

target 'AFMInfoBanner' do
  pod "AFMInfoBanner", :path => "../"
end

target 'Tests' do
  pod "AFMInfoBanner", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
